
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("c1bd311d-6509-4ede-ae52-b133eb4777ce")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class Model1Container
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Model1Container", "Model1Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Model1Container object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Model1Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Model1Container object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Model1Container")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MachinerySet() As ObjectSet(Of Machinery)
        Get
            If (_MachinerySet Is Nothing) Then
                _MachinerySet = MyBase.CreateObjectSet(Of Machinery)("MachinerySet")
            End If
            Return _MachinerySet
        End Get
    End Property

    Private _MachinerySet As ObjectSet(Of Machinery)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MachinerySet EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMachinerySet(ByVal machinery As Machinery)
        MyBase.AddObject("MachinerySet", machinery)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Model1", Name:="Machinery")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Machinery
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Machinery object.
    ''' </summary>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="imagePath">Initial value of the ImagePath property.</param>
    ''' <param name="property">Initial value of the Property property.</param>
    Public Shared Function CreateMachinery(name As Global.System.Int32, imagePath As Global.System.String, [property] As Global.System.String) As Machinery
        Dim machinery as Machinery = New Machinery
        machinery.Name = name
        machinery.ImagePath = imagePath
        machinery.[Property] = [property]
        Return machinery
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.Int32
        Get
            Return _Name
        End Get
        Set
            If (_Name <> Value) Then
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Name")
                OnNameChanged()
            End If
        End Set
    End Property

    Private _Name As Global.System.Int32
    Private Partial Sub OnNameChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ImagePath() As Global.System.String
        Get
            Return _ImagePath
        End Get
        Set
            OnImagePathChanging(value)
            ReportPropertyChanging("ImagePath")
            _ImagePath = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ImagePath")
            OnImagePathChanged()
        End Set
    End Property

    Private _ImagePath As Global.System.String
    Private Partial Sub OnImagePathChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnImagePathChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Property]() As Global.System.String
        Get
            Return _Property
        End Get
        Set
            OnPropertyChanging(value)
            ReportPropertyChanging("Property")
            _Property = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Property")
            OnPropertyChanged()
        End Set
    End Property

    Private _Property As Global.System.String
    Private Partial Sub OnPropertyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPropertyChanged()
    End Sub

    #End Region
End Class

#End Region

